openapi: 3.0.0
info:
  title: User and Group Management API
  description: An API for managing users, groups, and messaging between groups.
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local server

paths:
  /users:
    get:
      summary: Fetch all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    username:
                      type: string
                      example: john_doe
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: Create a new user
      requestBody:
        description: Username information
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                  example: john_doe
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
                  user_id:
                    type: integer
                    example: 1
                  username:
                    type: string
                    example: john_doe
        '400':
          description: Invalid input (missing username or username is empty)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /groups:
    get:
      summary: Fetch all groups
      responses:
        '200':
          description: A list of groups
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    group_name:
                      type: string
                      example: group_1
                    created_by:
                      type: string
                      example: john_doe
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      summary: Create a new group
      requestBody:
        description: Group name and username of the creator
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - group_name
                - username
              properties:
                group_name:
                  type: string
                  example: group_1
                username:
                  type: string
                  example: john_doe
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Group created successfully
                  group_id:
                    type: integer
                    example: 1
                  group_name:
                    type: string
                    example: group_1
                  created_by:
                    type: string
                    example: john_doe
        '400':
          description: Invalid input (missing group name or username)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '409':
          description: Group already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /groups/join:
    post:
      summary: Join an existing group
      requestBody:
        description: Group name and username of the joining user
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - group_name
                - username
              properties:
                group_name:
                  type: string
                  example: group_1
                username:
                  type: string
                  example: john_doe
      responses:
        '201':
          description: User joined group successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Joined group successfully
        '400':
          description: Invalid input (missing group name or username)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: User or group not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '409':
          description: User already in group
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /messages:
    get:
      summary: Fetch all messages for a specific group
      requestBody:
        description: Group name and username of the requesting user
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - group_name
                - username
              properties:
                group_name:
                  type: string
                  example: group_1
                username:
                  type: string
                  example: john_doe
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Hello, world!
                    username:
                      type: string
                      example: john_doe
                    created_at:
                      type: string
                      format: date-time
                      example: 2021-08-01 12:00:00
        '400':
          description: Invalid input (missing group name or username)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: User is not part of the group
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: User or group not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      summary: Send a message to a group
      requestBody:
        description: Group name, username, and message content
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - group_name
                - username
                - message
              properties:
                group_name:
                  type: string
                  example: group_1
                username:
                  type: string
                  example: john_doe
                message:
                  type: string
                  example: Hello, world!
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Message sent successfully
        '400':
          description: Invalid input (missing group name, username, or message)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: User is not part of the group
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: User or group not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /clear:
    delete:
      summary: Clear all database entries
      responses:
        '200':
          description: All entries cleared successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: All entries cleared successfully
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string